### ISSUE TITLE
DB_generation

### ISSUE THREAD

**Issue by SII-ShenggengLin** [knu-lcbc/Transformer_RetroTRAE#2]
Hello, author. I am very interested in your paper and am trying to run the code for this paper. But now I have some problems.
1. When I downloaded the CID-SMILES file from https://ftp.ncbi.nlm.nih.gov/pubchem/Compound/Extras/. And when running the DB_generation.py file, I always get SMILES Parse Error: syntax error while parsing: 16598 and RDKit ERROR: [21:19:43] SMILES Parse Error: syntax error while parsing: 16598. But I don't know how to fix it. If the author could give me a little help, I would be very grateful.

2. There is a comparison of top-1 accuracy with other methods in this paper, however, I did not find the relevant code in the github codebase. Is it convenient for the author to provide this part of the code?

My email is Linsg4521@sjtu.edu.cn.  Looking forward to your reply, thank you very much.
Best wishes!

**Comment by azpisruh** [comment]
1. Error handling in `DB_generation.py`  script is fixed and improved. Now you can generate the DB with the following command after downloading/extracting CID-SMILES.
```python
python src/DB_generation.py --raw_file='CID-SMILES' --dest='pubchem_AEs'
```

2. The comparison of top-1 accuracy with other methods are taken from the references given in Table 3 of the [original article](https://www.nature.com/articles/s41467-022-28857-w/tables/3).
