### ISSUE TITLE
atomic environment to SMILES

### ISSUE THREAD

**Issue by SII-ShenggengLin** [knu-lcbc/Transformer_RetroTRAE#3]
Hello, author. Programs can be used to obtain atomic environments according to SMILES. So I wonder if there is a program that can get SMILES based on the atomic environment.

**Comment by azpisruh** [comment]
Unfortunately, there is no such program available at the moment. 
However, there is a study in progress, please refer to following preprint, [link is here](https://chemrxiv.org/engage/chemrxiv/article-details/62273eb250b6211bf1ed8132).

**Comment by SII-ShenggengLin** [comment]
> Unfortunately, there is no such program available at the moment. However, there is a study in progress, please refer to following preprint, [link is here](https://chemrxiv.org/engage/chemrxiv/article-details/62273eb250b6211bf1ed8132).

ok,thanks very much
