### ISSUE TITLE
Could you provide the original version of the dataset?

### ISSUE THREAD

**Issue by otori-bird** [knu-lcbc/Transformer_RetroTRAE#4]
i unzipped '[raw_data.tar.bz2](https://github.com/knu-lcbc/RetroTRAE/blob/main/data/raw_data.tar.bz2)' but got the molecules represented by atomic environments. could you provide the original version of the dataset that is represented by SMILES or SMARTS?

Any help would be greatly appreciated.

**Comment by ashyrmamatov01** [comment]
Apologies for the late reply. 
We uploaded the reaction dataset in SMILES format ([here](https://github.com/knu-lcbc/RetroTRAE/blob/main/data/MIT_USPTO.tar.gz)). A line consists of a product-reactant with tab-delimited.
 Note that all of them are single product reactions.  Please refer to the [RetroTRAE paper](https://www.nature.com/articles/s41467-022-28857-w) for more about preprocessing details.

**Comment by otori-bird** [comment]
> Apologies for the late reply. We uploaded the reaction dataset in SMILES format ([here](https://github.com/knu-lcbc/RetroTRAE/blob/main/data/MIT_USPTO.tar.gz)). A line consists of a product-reactant with tab-delimited. Note that all of them are single product reactions. Please refer to the [RetroTRAE paper](https://www.nature.com/articles/s41467-022-28857-w) for more about preprocessing details.

thanks a lot! i will check it carefully.
