### ISSUE TITLE
NameError: name 'fp_names' is not defined

### ISSUE THREAD

**Issue by MSDP4DOM** [knu-lcbc/Transformer_RetroTRAE#8]
in `RetroTRAE\RetroTRAE\train.py`, I got an error: `NameError: name 'fp_names' is not defined`. Could you please check it? Many thanks.
`    args.src_vocab_size = fp_vocab_sizes[args.fp]
    args.trg_vocab_size = trg_vocab_sizes[args.model_type]
    args.src_seq_len = fp_seq_lens[args.fp]
    args.trg_seq_len = trg_seq_len` 
fp_vocab_sizes, trg_vocab_sizes, fp_seq_lens and trg_seq_len are not defined either.

**Comment by ashyrmamatov01** [comment]
Sorry for the confusion. 
Please use  `python src/train.py` script for training, instead of `RetroTRAE/train.py`.

**Comment by MSDP4DOM** [comment]
Sure, Thank you!
