### ISSUE TITLE
Question about accuracy

### ISSUE THREAD

**Issue by MSDP4DOM** [knu-lcbc/Transformer_RetroTRAE#9]
I apologize for any confusion caused. In Table 3 of your paper, your model shows the highest accuracy for retrosynthesis prediction. However, in the paper by Philippe Schwaller (https://doi.org/10.1021/acscentsci.9b00576), they achieved a top-1 accuracy above 90% on a common benchmark dataset for forward reaction prediction. I understand that the difference lies in the tasks being retrosynthesis prediction and forward reaction prediction, respectively. So I wonder why there is a huge gap between retrosynthesis and forward reaction prediction? If we consider single step reaction, in my opinion,  it seems intuitive to swap the source and target molecules for a single-step reaction in order to convert a retrosynthesis problem into a forward reaction prediction problem. Looking forword to your reply, Many thanks!

**Comment by azpisruh** [comment]
Hello,
The density of "one-to-many" mappings within the backward-reaction data is higher than forward-reaction one. This makes the translation harder, so the accuracy is lower. Consider that, there might be several ways to synthesize a specific target molecule. When you reverse the order, the target molecule maps multiple precursors through multiple reaction paths. Also, there is no additional information coming from solvents, reagents, or reaction conditions to help, it just confuses network to learn.
